### PR TITLE
fix: Bugs and edge cases related to implementation of retaining cluster terminal sessions

### LINKED ISSUE #1422: Follow-up bugs after retaining Cluster Terminal in Resource Browser
**The Problem To Be Solved**
Some follow-up bugs with the Cluster Terminal after the implementation of - https://github.com/devtron-labs/dashboard/issues/1405 :
1. On open cluster terminal we are getting loader (White Screen) instead of terminal with connecting message directly
2. [Prod]*We are not getting "Cluster Terminal" option on refresh page until we gets User Details response from API
3. For reconnecting terminal we have to click "reconnect" button 2 times 
4. On re-switching from pods terminal to pod manifest and other tabs, we are creating a new session
5. If we come back on Cluster list page directly from cluster overview page via click in navigation bar we don't have data available on UI
6. [Prod]*If we open cluster terminal directly from cluster list page we have no icon avail for terminal on the resource list page
7. Cluster terminal logs on switching from pod terminal are getting lost

### PR DESCRIPTION
**Pull request by prajjwal-devtron**
# Description

Fixes bugs and edge-cases related to the new implementation of retaining cluster terminal sessions.

Note - 
1. This PR also contains some minor refactor code in `ResourceList` component and `useTabs` hook.

Fixes #1422

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Tested for these bugs manually

# Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by vivek-devtron — APPROVED** [review]

File: src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx [hunk 1]
```diff
@@ -369,22 +397,9 @@ function NodeDetailComponent({
...
-                            setSelectedContainer={setSelectedContainer}
-                            containers={containers}
-                            setContainers={setContainers}
-                            selectedContainerName={selectedContainerName}
-                            setSelectedContainerName={setSelectedContainerName}
-                            switchSelectedContainer={switchSelectedContainer}
-                        />
-                    </Route>
-                    <Redirect to={`${path}/${NodeDetailTab.MANIFEST.toLowerCase()}`} />
+                    {!location.pathname.includes('/terminal') && (
```
Comment (prajjwal-devtron) [inline src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx:400]: Put `location.pathname.includes('/terminal')` in a state or ref

**Review by vivek-devtron — APPROVED** [review]
